# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170707_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_person_friends_+', to='api.Person'),
        ),
    ]
